### ISSUE TITLE
data missing from ftp site

### ISSUE THREAD

**Issue by MikeWooster** [nansencenter/openwind#17]
Hi, I'm fairly new to using nansat (and openwind).  I have just installed both packages and ran the test_sarwind.py file which failed to get the test data from the ftp site.  I do not yet have curl installed (I will address this soon), but looking at the full paths to the ftp site stored in openwind_test_archive.py, there doesn't appear to be any test data at ftp://ftp.nersc.no/pub/python_test_data/.

**Comment by rickedanielson** [comment]
ftp://ftp.nersc.no/pub/nansat/test_data/ seems to be the new directory to point to

**Comment by mortenwh** [comment]
Hi, thanks for noticing us! I have changed the ftp-path now and the tests are running on my system. Can you also have a try?
