### ISSUE TITLE
SARWind with Sentinel-1 may cause memory error if file is not small...

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/openwind#18]
There is a quite serious memory problem in openwind that needs to solved before it can work optimally with sentinel-1 data.

**Comment by knutfrode** [comment]
Could you add some more description of the problem?

**Comment by mortenwh** [comment]
Not sure what more I can say... I stopped for me in line 248 in sar_wind.py:

```

*/home/vagrant/miniconda/lib/python2.7/site-packages/openwind/sar_wind.pyc*
in _get_wind_direction_array*(self, aux_wind, eResampleAlg, *args,
**kwargs)*

    246         *if* u_array *is* None*:*

    247             *raise* Exception*(**'Could not read wind vectors'**)*

*--> 248*         *return* np*.*degrees*(*np*.*arctan2*(-*u_array*,* *-*
v_array*)),* \

    249                 wind_direction_time*,* \

    250                 np*.*sqrt*(*np*.*power*(*u_array*,* *2**)* *+* np*.*
power*(*v_array*,* *2**))*


*MemoryError*:


In [*3*]:

````

This is in the method were the model wind field is reprojected to return
wind directions defined on the SAR grid.

**Comment by knutfrode** [comment]
But how do you know it is a memory problem? Not obvious from the error message?

**Comment by mortenwh** [comment]
But it says ```MemoryError```?

**Comment by knutfrode** [comment]
Ah, I did not see that, only the first part of your comment is shown, and the three dots at the end for expanding does not work. I had to click "edit" on your message to see all.

**Comment by mortenwh** [comment]
aha - ok, is it better now?

**Comment by knutfrode** [comment]
Yes, now the whole comment is expanded.

**Comment by mortenwh** [comment]
Duplicate with #25
