### ISSUE TITLE
RS2 file in open_local_archive does not have corresponding NCEP

### ISSUE THREAD

**Issue by akorosov** [nansencenter/openwind#23]
The file 
RS2_20140326_054601_0076_SCWA_HHHV_SGF_316922_8221_9516957.zip
is too old.
Neither 
ftp://ftp.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/
nor
http://nomads.ncdc.noaa.gov/data/gfs4/
has NCEP data for that date.

Suggest to replace with e.g. 
RS2_20150503_063316_0076_SCWA_HHHV_SGF_394563_4420_11260944

**Comment by mortenwh** [comment]
Since it is proprietary and not easily shared, RS2 data is no longer tested
