### ISSUE TITLE
Memory problem identified

### ISSUE THREAD

**Issue by akorosov** [nansencenter/openwind#25]
In `SARWind.__init__` the method `self.set_aux_wind` is called **before** `self.resize`. That causes aux wind to be calculated at full res [10 000 x 10 000] pixels.

**Comment by akorosov** [comment]
The fix above seem to improve memory usage. It does not exceed 2GB. Windspeed for SCWA image was calculated OK. Tests don't pass however because quadpol image is too old. No NCEP data was found as in #23.

**Comment by mortenwh** [comment]
Solved between 9a1c3229f16ec9aaf7b4adc3f7021532bb2a7b0d and 9d1ad7df17b1bcf72e1615e5796913e5aa149217
