### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by fabiansurya** [nansencenter/openwind#27]
Hi, guys. I am just starting to use python, sorry for the basic questions.
First question, I managed to run Nansat, yet i still not get on how to install the Openwind.
> Add the top level folder openwind/ to your PYTHONPATH
> Add the subfolder openwind/openwind/ to your PATH (for command line usage)
> Test the installation by running the test script (test_sarwind.py) in openwind/tests

I have downloaded the openwind-master file with openwind and all the subfolders correctly.
I have not change the default PYTHONPATH, not really sure also about the PATH, but then i copy the open wind files to directory below
> /home/fabian/miniconda/pkgs/openwind

seems work, that i can run `from openwind import SARWind` in Python interpreter with no error
but it shows a lots of errors while i run the `python test_sarwind.py` in above directory
[test_sarwind error.txt](https://github.com/nansencenter/openwind/files/703777/test_sarwind.error.txt)
Could you please show me where did i make mistakes in between? surely i missed something.

Second, what kind of file format of Normalised Radar Cross Section (NRCS) works with openwind?
I am using the ESA SNAP software with Sentinel 1-A VV polarization.

Thank you in advance guys, for your time.
Fabian

**Comment by fabiansurya** [comment]
Hi, is there someone who can help me with the installation problem above? thank you :)

**Comment by brigitmaria** [comment]
> Hi, is there someone who can help me with the installation problem above? thank you :)

@fabiansurya Were u able to solve it? I am facing the same issue in here?
